services:
  postgres:
    container_name: haushalt_postgres
    image: postgres:16
    shm_size: 128mb
    environment:
      POSTGRES_DB: haushalt
      POSTGRES_USER: haushalt
      POSTGRES_PASSWORD: secret
    ports:
      - "5434:5432"
